In [27]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [28]:
train = pd.read_csv("train.csv", index_col= 'Id')
pd.options.display.max_columns = None

In [29]:
train.head()

v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
Id                                                                         
ID_279628684  190000.0       0      3       0     1       1     0    NaN   
ID_f29eb3ddd  135000.0       0      4       0     1       1     1    1.0   
ID_68de51c94       NaN       0      8       0     1       1     0    NaN   
ID_d671db89c  180000.0       0      5       0     1       1     1    1.0   
ID_d56d6f5f5  180000.0       0      5       0     1       1     1    1.0   

              r4h1  r4h2  r4h3  r4m1  r4m2  r4m3  r4t1  r4t2  r4t3  tamhog  \
Id                                                                           
ID_279628684     0     1     1     0     0     0     0     1     1       1   
ID_f29eb3ddd     0     1     1     0     0     0     0     1     1       1   
ID_68de51c94     0     0     0     0     1     1     0     1     1       1   
ID_d671db89c     0     2     2     1     1     2     1     3     4       4   
ID_d56d6f5f5     0     2     2     1     1     2     1     3     4       4   

              tamviv  escolari  rez_esc  hhsize  paredblolad  paredzocalo  \
Id                                                                          
ID_279628684       1        10      NaN       1            1            0   
ID_f29eb3ddd       1        12      NaN       1            0            0   
ID_68de51c94       1        11      NaN       1            0            0   
ID_d671db89c       4         9      1.0       4            1            0   
ID_d56d6f5f5       4        11      NaN       4            1            0   

              paredpreb  pareddes  paredmad  paredzinc  paredfibras  \
Id                                                                    
ID_279628684          0         0         0          0            0   
ID_f29eb3ddd          0         0         1          0            0   
ID_68de51c94          0         0         1          0            0   
ID_d671db89c          0         0         0          0            0   
ID_d56d6f5f5          0         0         0          0            0   

              paredother  pisomoscer  pisocemento  pisoother  pisonatur  \
Id                                                                        
ID_279628684           0           1            0          0          0   
ID_f29eb3ddd           0           0            0          0          0   
ID_68de51c94           0           1            0          0          0   
ID_d671db89c           0           1            0          0          0   
ID_d56d6f5f5           0           1            0          0          0   

              pisonotiene  pisomadera  techozinc  techoentrepiso  techocane  \
Id                                                                            
ID_279628684            0           0          0               1          0   
ID_f29eb3ddd            0           1          1               0          0   
ID_68de51c94            0           0          1               0          0   
ID_d671db89c            0           0          1               0          0   
ID_d56d6f5f5            0           0          1               0          0   

              techootro  cielorazo  abastaguadentro  abastaguafuera  \
Id                                                                    
ID_279628684          0          1                1               0   
ID_f29eb3ddd          0          1                1               0   
ID_68de51c94          0          1                1               0   
ID_d671db89c          0          1                1               0   
ID_d56d6f5f5          0          1                1               0   

              abastaguano  public  planpri  noelec  coopele  sanitario1  \
Id                                                                        
ID_279628684            0       1        0       0        0           0   
ID_f29eb3ddd            0       1        0       0        0           0   
ID_68de51c94          

In [30]:
train.Target.value_counts()

4    5996
2    1597
3    1209
1     755
Name: Target, dtype: int64

In [31]:
missing = train.isnull().sum().to_frame()
missing.sort_values(0, ascending= False)


0
rez_esc          7928
v18q1            7342
v2a1             6860
SQBmeaned           5
meaneduc            5
hogar_adul          0
parentesco10        0
parentesco11        0
parentesco12        0
idhogar             0
hogar_nin           0
dependency          0
hogar_mayor         0
hogar_total         0
edjefe              0
edjefa              0
instlevel1          0
instlevel2          0
parentesco9         0
parentesco7         0
parentesco8         0
estadocivil6        0
female              0
estadocivil1        0
estadocivil2        0
estadocivil3        0
estadocivil4        0
estadocivil5        0
estadocivil7        0
instlevel4          0
...               ...
elimbasu2           0
elimbasu3           0
elimbasu4           0
elimbasu5           0
epared1             0
techocane           0
epared2             0
epared3             0
etecho1             0
etecho2             0
etecho3             0
eviv1               0
energcocinar3       0
energcocinar2       0
energcocinar1       0
sanitario6          0
sanitario5          0
sanitario3          0
sanitario2          0
sanitario1          0
coopele             0
noelec              0
planpri             0
public              0
abastaguano         0
abastaguafuera      0
abastaguadentro     0
cielorazo           0
techootro           0
Target              0

[142 rows x 1 columns]

In [32]:

train = train.fillna(0)


In [33]:
train.isnull().sum()

v2a1               0
hacdor             0
rooms              0
hacapo             0
v14a               0
refrig             0
v18q               0
v18q1              0
r4h1               0
r4h2               0
r4h3               0
r4m1               0
r4m2               0
r4m3               0
r4t1               0
r4t2               0
r4t3               0
tamhog             0
tamviv             0
escolari           0
rez_esc            0
hhsize             0
paredblolad        0
paredzocalo        0
paredpreb          0
pareddes           0
paredmad           0
paredzinc          0
paredfibras        0
paredother         0
                  ..
bedrooms           0
overcrowding       0
tipovivi1          0
tipovivi2          0
tipovivi3          0
tipovivi4          0
tipovivi5          0
computer           0
television         0
mobilephone        0
qmobilephone       0
lugar1             0
lugar2             0
lugar3             0
lugar4             0
lugar5             0
lugar6       

In [34]:
from sklearn.preprocessing import LabelEncoder
# encode = LabelEncoder()

# column = ['dependency', 'edjefe', 'edjefa', 'dependency']
# for i in column:
#     train[i] = encode.fit_transform(train[i])
#     print(train[i], 'is ')

In [35]:
train = train.drop(['dependency', 'edjefe', 'edjefa', 'dependency', 'v2a1', 'idhogar', 'rez_esc'], axis = 1)

In [36]:
X = train.iloc[:, 1:-1]
y = train.iloc[:, -1:]

In [37]:
# y

In [38]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X = scale.fit_transform(X)
# y = scale.fit_transform(y)

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X ,y, test_size =0.25, random_state= 42)

In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

algo = RandomForestClassifier()
params={'n_estimators': list(range(40,61, 1))}
algo_cv = GridSearchCV(algo, params, cv=5)
algo_cv.fit(x_train, y_train)
y_pred = algo_cv.predict(x_test)

In [41]:
from sklearn.metrics import  accuracy_score, confusion_matrix, classification_report

print("Classification report ", classification_report(y_pred, y_test))


Classification report               precision    recall  f1-score   support

          1       0.80      0.94      0.87       176
          2       0.84      0.92      0.87       354
          3       0.70      0.96      0.81       224
          4       0.99      0.90      0.94      1636

avg / total       0.93      0.91      0.92      2390



In [42]:
print("Confusion matrix", confusion_matrix(y_pred, y_test))

Confusion matrix [[ 166    8    2    0]
 [   8  324   15    7]
 [   0    3  216    5]
 [  33   52   75 1476]]


In [43]:
print("accuracy", accuracy_score(y_pred, y_test))

accuracy 0.9129707112970711


In [44]:
test = pd.read_csv("test.csv", index_col="Id")

In [45]:
test.head()

v2a1  hacdor  rooms  hacapo  v14a  refrig  v18q  v18q1  \
Id                                                                         
ID_2f6873615       NaN       0      5       0     1       1     0    NaN   
ID_1c78846d2       NaN       0      5       0     1       1     0    NaN   
ID_e5442cf6a       NaN       0      5       0     1       1     0    NaN   
ID_a8db26a79       NaN       0     14       0     1       1     1    1.0   
ID_a62966799  175000.0       0      4       0     1       1     1    1.0   

              r4h1  r4h2  r4h3  r4m1  r4m2  r4m3  r4t1  r4t2  r4t3  tamhog  \
Id                                                                           
ID_2f6873615     1     1     2     0     1     1     1     2     3       3   
ID_1c78846d2     1     1     2     0     1     1     1     2     3       3   
ID_e5442cf6a     1     1     2     0     1     1     1     2     3       3   
ID_a8db26a79     0     1     1     0     0     0     0     1     1       1   
ID_a62966799     0     0     0     0     1     1     0     1     1       1   

              tamviv  escolari  rez_esc  hhsize  paredblolad  paredzocalo  \
Id                                                                          
ID_2f6873615       3         0      NaN       3            1            0   
ID_1c78846d2       3        16      NaN       3            1            0   
ID_e5442cf6a       3        17      NaN       3            1            0   
ID_a8db26a79       1        16      NaN       1            1            0   
ID_a62966799       1        11      NaN       1            1            0   

              paredpreb  pareddes  paredmad  paredzinc  paredfibras  \
Id                                                                    
ID_2f6873615          0         0         0          0            0   
ID_1c78846d2          0         0         0          0            0   
ID_e5442cf6a          0         0         0          0            0   
ID_a8db26a79          0         0         0          0            0   
ID_a62966799          0         0         0          0            0   

              paredother  pisomoscer  pisocemento  pisoother  pisonatur  \
Id                                                                        
ID_2f6873615           0           1            0          0          0   
ID_1c78846d2           0           1            0          0          0   
ID_e5442cf6a           0           1            0          0          0   
ID_a8db26a79           0           1            0          0          0   
ID_a62966799           0           1            0          0          0   

              pisonotiene  pisomadera  techozinc  techoentrepiso  techocane  \
Id                                                                            
ID_2f6873615            0           0          1               0          0   
ID_1c78846d2            0           0          1               0          0   
ID_e5442cf6a            0           0          1               0          0   
ID_a8db26a79            0           0          1               0          0   
ID_a62966799            0           0          1               0          0   

              techootro  cielorazo  abastaguadentro  abastaguafuera  \
Id                                                                    
ID_2f6873615          0          1                1               0   
ID_1c78846d2          0          1                1               0   
ID_e5442cf6a          0          1                1               0   
ID_a8db26a79          0          1                1               0   
ID_a62966799          0          1                1               0   

              abastaguano  public  planpri  noelec  coopele  sanitario1  \
Id                                                                        
ID_2f6873615            0       1        0       0        0           0   
ID_1c78846d2            0       1        0       0        0           0   
ID_e5442cf6a          

In [46]:
test = test.fillna(0)

In [47]:
Id = test.index


In [48]:
def preprocess(data):
    data = data.fillna(0)
    data = data.drop(['dependency', 'edjefe', 'edjefa', 'dependency', 'v2a1', 'idhogar', 'rez_esc'], axis = 1)
    data = data.iloc[:, 1:]
    scale = StandardScaler()
    data = scale.fit_transform(data)
    
    
    return data
  

In [49]:
test = preprocess(test)

In [51]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

algo = RandomForestClassifier()
params={'n_estimators': list(range(40,61, 1))}
algo_cv = GridSearchCV(algo, params, cv=5)
algo_cv.fit(X, y)
y_pred = algo_cv.predict(test)

In [54]:
algo_cv.score(test, y_pred)

1.0

In [59]:
pred = pd.DataFrame({'Id' : Id, "Target" : y_pred})

In [60]:
pred.to_csv("submission.csv", index=False)

In [61]:
p = pd.read_csv("submission.csv")

In [63]:
p.Target.value_counts()

4    19071
2     3213
3      814
1      758
Name: Target, dtype: int64